import { useState } from 'react'
import Head from 'next/head'
import CursorLoader from '@react-sandbox/cursor-loader'

export default function Home() {
  const [load, setLoad] = useState<number>(25)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <CursorLoader load={load} size="md" />

      <main>
        <button onClick={() => setLoad(0)}>Clear Load</button>
        <button onClick={() => setLoad(20)}>Set Load 20</button>
        <button onClick={() => setLoad(50)}>Set Load 50</button>
        <button onClick={() => setLoad(75)}>Set Load 75</button>
        <button onClick={() => setLoad(100)}>Set Load 100</button>
      </main>
    </>
  )
}
