import { useState } from 'react'
import Head from 'next/head'
import CursorLoader from '@react-sandbox/cursor-loader'

export default function Home() {
  const [load, setLoad] = useState<number>(25)
  const [text, setText] = useState<string>('Set Load 100')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <CursorLoader
        load={load}
        size="md"
        onComplete={() => setText('Completed!')}
      />

      <main>
        <button className="load-0" onClick={() => setLoad(0)}>
          Clear Load
        </button>
        <button className="load-25" onClick={() => setLoad(25)}>
          Set Load 25
        </button>
        <button className="load-50" onClick={() => setLoad(50)}>
          Set Load 50
        </button>
        <button className="load-75" onClick={() => setLoad(75)}>
          Set Load 75
        </button>
        <button className="load-100" onClick={() => setLoad(100)}>
          {text}
        </button>
      </main>
    </>
  )
}
